### ISSUE TITLE
Support to Android Studio 2.3

### ISSUE THREAD

**Issue by erikjhordan-rey** [riggaroo/android-arch-components-date-countdown#1]
Hi @riggaroo  Rebecca !  First of all, thanks for your contribution Good job!

Is not an issue rather it is something like an improvement for developers who use a stable android studio version like `2.3` and wants compile this project out of `android studio 3.0 preview`.

I propose create another `branch` with two little changes to run this project in `AS 2.3`
(We are not all so risky to use the Android Studio Previews ;) )
```
  defaultConfig {
      ....
        //jackOptions is deprecated in android Studio 3.0 but this is for educational purposes
        // to compile this project in android studio 2.3 stable version.
        jackOptions {
            enabled true
        }
    } 
```

```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'
    }

```

It would also be nice if you add on readme file the project only works in `Android Studio 3.0 preview`.

**Comment by riggaroo** [comment]
Thanks for the suggestion. I've created a new branch for stable version of AS 👍
