### ISSUE TITLE
[FEATURE REQUEST] Can you please add flavour type mock?

### ISSUE THREAD

**Issue by Manikkumar1988** [riggaroo/android-arch-components-date-countdown#4]

**Comment by riggaroo** [comment]
For what purpose?

**Comment by Manikkumar1988** [comment]
Often during development stages(or enhancing the UI elements) of enterprise application, we are required to navigate 3 to 6 level of screens down to test particular feature. 

Allowing mock flavour would fetch data from locally(json/hard-coded strings) and would easier to navigate desired screen without waiting for actual data to be downloaded and navigation.

**Comment by riggaroo** [comment]
Feel free to fork this example and update your fork with a mock flavour. This example doesn't render different data for different environments, and probably never will.
