### ISSUE TITLE
Unable to run android studio Preview3.0

### ISSUE THREAD

**Issue by Manikkumar1988** [riggaroo/android-arch-components-date-countdown#5]
`Gradle sync failed: Could not find com.android.tools.build:gradle:3.0.0-alpha7.
				Searched in the following locations:
				file:/private/var/folders/d_/vfn7wc5s6k7_9_lgdvmg0wj80000gn/T/AppTranslocation/3D7F470B-A0DA-4462-81CA-D3CD72D0183F/d/Android Studio 3.0 Preview.app/Contents/gradle/m2repository/com/android/tools/build/gradle/3.0.0-alpha7/gradle-3.0.0-alpha7.pom
				file:/private/var/folders/d_/vfn7wc5s6k7_9_lgdvmg0wj80000gn/T/AppTranslocation/3D7F470B-A0DA-4462-81CA-D3CD72D0183F/d/Android Studio 3.0 Preview.app/Contents/gradle/m2repository/com/android/tools/build/gradle/3.0.0-alpha7/gradle-3.0.0-alpha7.jar
				https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-alpha7/gradle-3.0.0-alpha7.pom
				https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-alpha7/gradle-3.0.0-alpha7.jar
				Required by:
				project :
				Consult IDE log for more details (Help | Show Log) (8s 18ms)`

**Comment by riggaroo** [comment]
I've updated the dependencies. It should be working with the latest version of Android Studio. (Beta 7)
