### ISSUE TITLE
[QUESTION] How do we inject event repository to activity?

### ISSUE THREAD

**Issue by Manikkumar1988** [riggaroo/android-arch-components-date-countdown#6]
Its not related to any feature of the application, Im just curious to know the syntax to inject any into the activity/fragment (Android components). not the POJO classes

**Comment by Manikkumar1988** [comment]
It would be of great help, if you can share code snippet alone without modifying on project!nt
or pointing to blog or developer site

**Comment by riggaroo** [comment]
Hi @Manikkumar1988 I've updated the sample to use the new Dagger with proper Android support.
This change is on master.
To inject something into the activity or fragment, now you can just annotate the variable with it.

```
@Inject
EventRepository eventRepository;
```
