### ISSUE TITLE
Can't seem to find the DaggerCountdownComponent

### ISSUE THREAD

**Issue by bilthon** [riggaroo/android-arch-components-date-countdown#7]
I'm trying to compile this project on the `android-studio-2-3` branch, but the class `za.co.riggaroo.datecountdown.injection.DaggerCountdownComponent` is missing.

**Comment by Manikkumar1988** [comment]
It should be auto-generated as part of Dagger compilation, no source shall be provided for the same. 

My guess is that, there should have been an another compile time error preventing auto-generation of "DaggerCountdownComponent".

I encourage to dig deep on gradle/event console
