### ISSUE TITLE
Android Arch 1.1 Support

### ISSUE THREAD

**Issue by zishanj** [riggaroo/android-arch-components-date-countdown#9]
Any luck to update this sample to support version 1.1.0? `ViewModelProviders.of` is deprecated and is no longer supported by latest version.

**Comment by riggaroo** [comment]
Hi there, 
Master branch is updated with version 1.1.0 of architecture components. I see in the documentation `ViewModelProviders()` is deprecated, not the use of the `ViewModelProviders.of()`.

https://developer.android.com/reference/android/arch/lifecycle/ViewModelProviders.html

Unless I'm missing something - let me know where you see its not up to date.

**Comment by zishanj** [comment]
In my Android Studio its not recognising `ViewModelProviders.of()` when I use v1.1. There is only `ViewModelProvider`.

**Comment by riggaroo** [comment]
Have you checked out master branch?

**Comment by zishanj** [comment]
Its really strange... Yesterday I tried to developed sample project after following your blog and v1.1 was not recognizing `ViewModelProviders`. Today I restarted my system and Android Studio and it started working. :/
